version: '3'
services:
  python:
    container_name: ppc
    build:
      context: .
      dockerfile: dockerfile
      target: dev
    volumes:
      - ../:/usr/src/ppc
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"